import React, {useEffect,useState} from 'react';
import {SafeAreaView,ScrollView,View,Text,StyleSheet,Pressable,Switch} from 'react-native';
import {StatusBar} from 'expo-status-bar';
const mockSignals: any[] = [];
import {getSignals} from "../src/lib/api";
import {enableNotifications,sendTestNotification} from '../src/lib/notifications';
export default function Home(){ const [signals,setSignals]=useState<any[]>([]); useEffect(()=>{getSignals().then(setSignals).catch(console.error)},[]);
 const [notifications,setNotifications]=useState(false);
 async function toggle(v:boolean){if(v){const ok=await enableNotifications();setNotifications(ok);if(ok) await sendTestNotification();}else setNotifications(false)}
 return <SafeAreaView style={s.safe}><StatusBar style="light"/><ScrollView contentContainerStyle={s.page}>
  <Text style={s.brand}>MOMENTUM</Text><Text style={s.title}>NSE/BSE Scanner</Text><Text style={s.sub}>Personal paper-trading dashboard • ₹50,000 model capital</Text>
  <View style={s.row}><View style={s.metric}><Text style={s.mlabel}>Daily target</Text><Text style={s.mvalue}>₹500</Text></View><View style={s.metric}><Text style={s.mlabel}>Mode</Text><Text style={s.mvalue}>PAPER</Text></View></View>
  <View style={s.card}><View style={s.between}><View><Text style={s.cardTitle}>Push alerts</Text><Text style={s.muted}>Notify only after signal filters agree.</Text></View><Switch value={notifications} onValueChange={toggle}/></View></View>
  <Text style={s.section}>Positive momentum</Text>{signals.map(x=><View key={x.symbol} style={s.card}><View style={s.between}><View><Text style={s.symbol}>{x.symbol}</Text><Text style={s.muted}>{x.name}</Text></View><View><Text style={s.positive}>+{x.changePct.toFixed(2)}%</Text><Text style={s.score}>Score {x.score}/100</Text></View></View><Text style={s.price}>₹{x.price.toFixed(2)}</Text><Text style={s.reason}>{x.reason}</Text><Text style={s.meta}>RVOL {x.relativeVolume.toFixed(1)}× • {x.trend} • {x.observedAt}</Text><Text style={s.meta}>PAPER BUY • Entry ₹{Number(x.entry).toFixed(2)} • T1 ₹{Number(x.target_1).toFixed(2)} • T2 ₹{Number(x.target_2).toFixed(2)}</Text><Text style={s.risk}>EXIT/SELL BELOW ₹{Number(x.invalidation).toFixed(2)}</Text></View>)}
  <Pressable style={s.button} onPress={sendTestNotification}><Text style={s.buttonText}>Send test notification</Text></Pressable>
  <Text style={s.disclaimer}>Observed momentum is not a prediction or buy recommendation. Live Angel One execution is intentionally disabled in V1.</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#07111f'},page:{padding:20,paddingBottom:50},brand:{color:'#5ee6a8',fontWeight:'800',letterSpacing:3,marginTop:8},title:{color:'white',fontSize:30,fontWeight:'800',marginTop:5},sub:{color:'#91a0b5',marginTop:5,marginBottom:18},row:{flexDirection:'row',gap:12},metric:{flex:1,backgroundColor:'#101d2e',padding:16,borderRadius:16},mlabel:{color:'#91a0b5'},mvalue:{color:'white',fontSize:22,fontWeight:'800',marginTop:4},section:{color:'white',fontSize:20,fontWeight:'800',marginTop:24,marginBottom:10},card:{backgroundColor:'#101d2e',padding:16,borderRadius:18,marginBottom:12},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10},cardTitle:{color:'white',fontSize:17,fontWeight:'700'},muted:{color:'#91a0b5',marginTop:3},symbol:{color:'white',fontSize:20,fontWeight:'800'},positive:{color:'#5ee6a8',fontWeight:'800',fontSize:18,textAlign:'right'},score:{color:'#91a0b5',fontSize:12,textAlign:'right'},price:{color:'white',fontSize:26,fontWeight:'800',marginTop:15},reason:{color:'#d8e1ed',marginTop:8,lineHeight:20},meta:{color:'#5ee6a8',marginTop:10,fontWeight:'600'},risk:{color:'#f0b66b',marginTop:8},button:{backgroundColor:'#5ee6a8',padding:16,borderRadius:15,alignItems:'center',marginTop:8},buttonText:{color:'#07111f',fontWeight:'800'},disclaimer:{color:'#718096',fontSize:12,lineHeight:18,marginTop:16}})
